import type {
  Video,
  Course,
  OpenSlot,
  MembershipPlan,
} from "@/types";

// ─── Videos ──────────────────────────────────────────────────────────────────

export const MOCK_VIDEOS: Video[] = [
  {
    id: "v1",
    slug: "ranní-protazeni-10-minut",
    title: "Ranní protažení – 10 minut",
    description: "Ideální start dne. Zahřejeme celé tělo jemnými pohyby a uvolníme klouby.",
    thumbnailUrl: "/thumbnails/morning-stretch.jpg",
    durationSeconds: 600,
    accessLevel: "FREE",
    providerId: "placeholder-mux-id-1",
    bodyParts: ["celé tělo"],
    difficulty: "začátečník",
    problemTypes: ["mobilita", "prevence"],
    equipment: ["podložka"],
    tags: ["ráno", "protažení", "začátečník"],
    publishedAt: "2024-01-10T08:00:00Z",
  },
  {
    id: "v2",
    slug: "zada-ulevova-sestava",
    title: "Záda – úlevová sestava",
    description: "Přesně cílená cvičení pro úlevu od bolesti zad. Ideální po dlouhém sezení.",
    thumbnailUrl: "/thumbnails/back-relief.jpg",
    durationSeconds: 900,
    accessLevel: "FREE",
    providerId: "placeholder-mux-id-2",
    bodyParts: ["záda"],
    difficulty: "začátečník",
    problemTypes: ["bolest", "rehabilitace"],
    equipment: ["podložka"],
    tags: ["záda", "bolest", "kancelář"],
    publishedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "v3",
    slug: "kycle-mobilita-hloubkova",
    title: "Kyčle – hloubková mobilita",
    description: "Séria cviků pro uvolnění kyčlí, které tuhnou při sezení u stolu.",
    thumbnailUrl: "/thumbnails/hip-mobility.jpg",
    durationSeconds: 1200,
    accessLevel: "MEMBER",
    providerId: "placeholder-mux-id-3",
    bodyParts: ["kyčle"],
    difficulty: "mírně pokročilý",
    problemTypes: ["tuhnutí", "mobilita"],
    equipment: ["podložka"],
    tags: ["kyčle", "mobilita", "VIP"],
    publishedAt: "2024-02-01T10:00:00Z",
  },
  {
    id: "v4",
    slug: "rameno-rehabilitace-po-urazu",
    title: "Rameno – rehabilitace po úrazu",
    description: "Bezpečný postup pro návrat pohyblivosti ramene po zranění.",
    thumbnailUrl: "/thumbnails/shoulder-rehab.jpg",
    durationSeconds: 1500,
    accessLevel: "MEMBER",
    providerId: "placeholder-mux-id-4",
    bodyParts: ["rameno"],
    difficulty: "mírně pokročilý",
    problemTypes: ["rehabilitace", "bolest"],
    equipment: ["odporová guma"],
    tags: ["rameno", "rehabilitace"],
    publishedAt: "2024-02-10T10:00:00Z",
  },
  {
    id: "v5",
    slug: "dech-pro-pohodu-a-silu",
    title: "Dech pro pohodu a sílu",
    description: "Naučte se správně dýchat. Cvičení pro hluboký stabilizační systém.",
    thumbnailUrl: "/thumbnails/breathing.jpg",
    durationSeconds: 1800,
    accessLevel: "VIP",
    providerId: "placeholder-mux-id-5",
    bodyParts: ["dech", "core"],
    difficulty: "mírně pokročilý",
    problemTypes: ["posílení", "prevence"],
    equipment: ["podložka"],
    tags: ["dech", "core", "VIP"],
    publishedAt: "2024-02-20T10:00:00Z",
  },
  {
    id: "v6",
    slug: "nocni-uvolneni-pred-spanim",
    title: "Noční uvolnění před spaním",
    description: "Zklidňující rutina. Uvolní napětí celého dne a připraví tělo ke spánku.",
    thumbnailUrl: "/thumbnails/night-relax.jpg",
    durationSeconds: 1080,
    accessLevel: "FREE",
    providerId: "placeholder-mux-id-6",
    bodyParts: ["celé tělo"],
    difficulty: "začátečník",
    problemTypes: ["mobilita", "prevence"],
    equipment: ["podložka"],
    tags: ["večer", "uvolnění", "spánek"],
    publishedAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "v7",
    slug: "noha-koleno-stabilizace",
    title: "Noha & koleno – stabilizace",
    description: "Cílené posilování pro stabilní koleno a zdravou nohu.",
    thumbnailUrl: "/thumbnails/knee-stability.jpg",
    durationSeconds: 1320,
    accessLevel: "VIP",
    providerId: "placeholder-mux-id-7",
    bodyParts: ["noha"],
    difficulty: "pokročilý",
    problemTypes: ["slabost", "rehabilitace"],
    equipment: ["odporová guma", "podložka"],
    tags: ["koleno", "noha", "VIP"],
    publishedAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "v8",
    slug: "office-cviceni-v-kancelare",
    title: "Office cvičení v kanceláři",
    description: "5 cviků které zvládnete u stolu. Bez podložky, bez převlékání.",
    thumbnailUrl: "/thumbnails/office.jpg",
    durationSeconds: 480,
    accessLevel: "FREE",
    providerId: "placeholder-mux-id-8",
    bodyParts: ["záda", "krk", "rameno"],
    difficulty: "začátečník",
    problemTypes: ["prevence", "tuhnutí"],
    equipment: ["žádné"],
    tags: ["kancelář", "sezení", "rychlé"],
    publishedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "v9",
    slug: "vip-plus-exkluzivni-trening",
    title: "VIP PLUS – Exkluzivní trénink",
    description: "Komplexní tréninková jednotka jen pro VIP PLUS členy. Intenzivní a efektivní.",
    thumbnailUrl: "/thumbnails/vip-plus.jpg",
    durationSeconds: 2700,
    accessLevel: "VIP_PLUS",
    providerId: "placeholder-mux-id-9",
    bodyParts: ["celé tělo"],
    difficulty: "pokročilý",
    problemTypes: ["posílení"],
    equipment: ["podložka", "odporová guma", "činky"],
    tags: ["VIP PLUS", "pokročilý", "komplexní"],
    publishedAt: "2024-04-01T10:00:00Z",
  },
];

// ─── Courses ─────────────────────────────────────────────────────────────────

export const MOCK_COURSES: Course[] = [
  {
    id: "c1",
    slug: "office-cviceni",
    title: "OFFICE CVIČENÍ",
    subtitle: "Cvičte u stolu a zůstaňte bez bolestí",
    description:
      "Kompletní program pro ty, kteří tráví celý den u počítače. Naučíte se pohybové návyky a micro-cvičení, která zachrání vaše tělo od bolestí z dlouhého sezení.",
    thumbnailUrl: "/thumbnails/course-office.jpg",
    priceKc: 990,
    lessons: [
      { id: "l1", order: 1, title: "Proč sedění ničí tělo", durationSeconds: 720, accessLevel: "FREE" },
      { id: "l2", order: 2, title: "Nastavení pracovního místa", durationSeconds: 900, accessLevel: "FREE" },
      { id: "l3", order: 3, title: "Ranní rutina – 5 minut", durationSeconds: 300, accessLevel: "FREE" },
      { id: "l4", order: 4, title: "Micro-cvičení každou hodinu", durationSeconds: 600, accessLevel: "MEMBER" },
      { id: "l5", order: 5, title: "Záda a bederní páteř", durationSeconds: 1200, accessLevel: "MEMBER" },
      { id: "l6", order: 6, title: "Krk a ramena", durationSeconds: 1080, accessLevel: "MEMBER" },
      { id: "l7", order: 7, title: "Odpolední reset", durationSeconds: 480, accessLevel: "MEMBER" },
    ],
    tags: ["kancelář", "záda", "prevence"],
    publishedAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "c2",
    slug: "bolava-zada",
    title: "BOLAVÁ ZÁDA",
    subtitle: "Zbavte se bolesti a pochopte co ji způsobuje",
    description:
      "Přesný program pro lidi trpící bolestmi zad. Krok za krokem – od pochopení příčin až po konkrétní cvičení pro trvalou úlevu.",
    thumbnailUrl: "/thumbnails/course-back.jpg",
    priceKc: 1290,
    lessons: [
      { id: "l8", order: 1, title: "Anatomie zad jednoduše", durationSeconds: 900, accessLevel: "FREE" },
      { id: "l9", order: 2, title: "Co záda nesnáší", durationSeconds: 720, accessLevel: "FREE" },
      { id: "l10", order: 3, title: "Akutní úleva – první pomoc", durationSeconds: 600, accessLevel: "MEMBER" },
      { id: "l11", order: 4, title: "Protažení bederní páteře", durationSeconds: 1200, accessLevel: "MEMBER" },
      { id: "l12", order: 5, title: "Posilování hlubokého stabilizátoru", durationSeconds: 1500, accessLevel: "MEMBER" },
      { id: "l13", order: 6, title: "Preventivní program – 3× týdně", durationSeconds: 1800, accessLevel: "MEMBER" },
    ],
    tags: ["záda", "bolest", "rehabilitace"],
    publishedAt: "2024-02-15T10:00:00Z",
  },
  {
    id: "c3",
    slug: "zdravotni-noha",
    title: "NOHA",
    subtitle: "Zdravá chodidla, kolena a hlezenní klouby",
    description:
      "Péče o nohu od prstů až po kyčel. Vhodné po zranění i jako prevence.",
    thumbnailUrl: "/thumbnails/course-leg.jpg",
    priceKc: 990,
    lessons: [
      { id: "l14", order: 1, title: "Chodidlo – základ všeho", durationSeconds: 900, accessLevel: "FREE" },
      { id: "l15", order: 2, title: "Hlezenní kloub – mobilita", durationSeconds: 900, accessLevel: "MEMBER" },
      { id: "l16", order: 3, title: "Koleno – stabilizace", durationSeconds: 1200, accessLevel: "MEMBER" },
      { id: "l17", order: 4, title: "Stehno a kyčel", durationSeconds: 1200, accessLevel: "MEMBER" },
    ],
    tags: ["noha", "koleno", "rehabilitace"],
    publishedAt: "2024-03-05T10:00:00Z",
  },
  {
    id: "c4",
    slug: "kycle",
    title: "KYČLE",
    subtitle: "Mobilní kyčle = zdravá záda",
    description:
      "Tuhé kyčle jsou nejčastější příčina bolestí zad. Tento kurz vám vrátí mobilitu a uvolní kyčelní klouby do plného rozsahu.",
    thumbnailUrl: "/thumbnails/course-hips.jpg",
    priceKc: 1090,
    lessons: [
      { id: "l18", order: 1, title: "Anatomie kyčelního kloubu", durationSeconds: 720, accessLevel: "FREE" },
      { id: "l19", order: 2, title: "Testování vaší mobility", durationSeconds: 600, accessLevel: "FREE" },
      { id: "l20", order: 3, title: "Uvolnění flexorů kyčle", durationSeconds: 1200, accessLevel: "MEMBER" },
      { id: "l21", order: 4, title: "Rotátory a abduktory", durationSeconds: 1200, accessLevel: "MEMBER" },
      { id: "l22", order: 5, title: "Kompletní mobilizační sestava", durationSeconds: 1800, accessLevel: "MEMBER" },
    ],
    tags: ["kyčle", "mobilita", "záda"],
    publishedAt: "2024-03-20T10:00:00Z",
  },
  {
    id: "c5",
    slug: "rameno",
    title: "RAMENO",
    subtitle: "Obnovte funkci a zbavte se bolesti ramene",
    description:
      "Kompletní průvodce pro zdravé rameno. Vhodné po úrazech, při přetížení nebo jako prevence pro sportovce.",
    thumbnailUrl: "/thumbnails/course-shoulder.jpg",
    priceKc: 1090,
    lessons: [
      { id: "l23", order: 1, title: "Ramenní kloub – jak funguje", durationSeconds: 900, accessLevel: "FREE" },
      { id: "l24", order: 2, title: "Diagnostika vašeho ramene", durationSeconds: 720, accessLevel: "FREE" },
      { id: "l25", order: 3, title: "Rotátorová manžeta – základ", durationSeconds: 1200, accessLevel: "MEMBER" },
      { id: "l26", order: 4, title: "Lopatkové stabilizátory", durationSeconds: 1200, accessLevel: "MEMBER" },
      { id: "l27", order: 5, title: "Síla a stabilita", durationSeconds: 1500, accessLevel: "MEMBER" },
    ],
    tags: ["rameno", "rehabilitace", "posílení"],
    publishedAt: "2024-04-05T10:00:00Z",
  },
  {
    id: "c6",
    slug: "dech",
    title: "DECH",
    subtitle: "Dýchejte správně. Fungujte lépe.",
    description:
      "Správný dech je základ pohybu, výkonu i regenerace. Naučíme se dechovou mechaniku, práci bránice a dech jako nástroj pro snížení stresu.",
    thumbnailUrl: "/thumbnails/course-breath.jpg",
    priceKc: 890,
    lessons: [
      { id: "l28", order: 1, title: "Jak správně dýcháme (a jak ne)", durationSeconds: 900, accessLevel: "FREE" },
      { id: "l29", order: 2, title: "Bránice – hlavní dechový sval", durationSeconds: 1080, accessLevel: "MEMBER" },
      { id: "l30", order: 3, title: "DNS dechová cvičení", durationSeconds: 1200, accessLevel: "MEMBER" },
      { id: "l31", order: 4, title: "Dech a pohybový výkon", durationSeconds: 900, accessLevel: "MEMBER" },
    ],
    tags: ["dech", "bránice", "stres"],
    publishedAt: "2024-04-20T10:00:00Z",
  },
  {
    id: "c7",
    slug: "rodic-a-dite",
    title: "RODIČ A DÍTĚ",
    subtitle: "Pohyb jako společná hra a dobrodružství",
    description:
      "Program pro rodiče a děti 3–8 let. Pohybové hry, cvičení a aktivity, které baví celou rodinu a přirozeně rozvíjejí motoriku dítěte.",
    thumbnailUrl: "/thumbnails/course-parent-child.jpg",
    priceKc: 790,
    lessons: [
      { id: "l32", order: 1, title: "Proč cvičit s dítětem", durationSeconds: 600, accessLevel: "FREE" },
      { id: "l33", order: 2, title: "Ranní pohybová hra", durationSeconds: 900, accessLevel: "MEMBER" },
      { id: "l34", order: 3, title: "Zvířecí pohyby", durationSeconds: 1080, accessLevel: "MEMBER" },
      { id: "l35", order: 4, title: "Rovnovážné hry", durationSeconds: 900, accessLevel: "MEMBER" },
      { id: "l36", order: 5, title: "Silové hry pro tátu a mámu", durationSeconds: 1200, accessLevel: "MEMBER" },
    ],
    tags: ["děti", "rodina", "hry"],
    publishedAt: "2024-05-01T10:00:00Z",
  },
];

// ─── Open slots ───────────────────────────────────────────────────────────────

function addDays(base: Date, days: number): Date {
  const d = new Date(base);
  d.setDate(d.getDate() + days);
  return d;
}

const baseDate = new Date("2026-06-09T00:00:00");

export const MOCK_OPEN_SLOTS: OpenSlot[] = [
  { id: "s1", dateTime: new Date(addDays(baseDate, 0).setHours(9, 0)).toISOString(), durationMinutes: 60, type: "online", isBooked: false },
  { id: "s2", dateTime: new Date(addDays(baseDate, 0).setHours(11, 0)).toISOString(), durationMinutes: 60, type: "online", isBooked: true },
  { id: "s3", dateTime: new Date(addDays(baseDate, 1).setHours(10, 0)).toISOString(), durationMinutes: 90, type: "domů", isBooked: false },
  { id: "s4", dateTime: new Date(addDays(baseDate, 2).setHours(9, 0)).toISOString(), durationMinutes: 60, type: "online", isBooked: false },
  { id: "s5", dateTime: new Date(addDays(baseDate, 2).setHours(14, 0)).toISOString(), durationMinutes: 60, type: "na místě", isBooked: false },
  { id: "s6", dateTime: new Date(addDays(baseDate, 3).setHours(16, 0)).toISOString(), durationMinutes: 60, type: "online", isBooked: false },
  { id: "s7", dateTime: new Date(addDays(baseDate, 5).setHours(10, 0)).toISOString(), durationMinutes: 90, type: "domů", isBooked: false },
  { id: "s8", dateTime: new Date(addDays(baseDate, 5).setHours(13, 0)).toISOString(), durationMinutes: 60, type: "online", isBooked: false },
  { id: "s9", dateTime: new Date(addDays(baseDate, 7).setHours(9, 0)).toISOString(), durationMinutes: 60, type: "online", isBooked: false },
  { id: "s10", dateTime: new Date(addDays(baseDate, 8).setHours(11, 0)).toISOString(), durationMinutes: 90, type: "na místě", isBooked: false },
];

// ─── Membership plans ─────────────────────────────────────────────────────────

export const MOCK_MEMBERSHIP_PLANS: MembershipPlan[] = [
  {
    id: "mp1",
    tier: "MEMBER",
    name: "MEMBER",
    priceKcMonth: 199,
    highlighted: false,
    features: [
      "Přístup k celé VIP videoknihovně",
      "Nová videa každý týden",
      "Filtry dle části těla a problému",
      "Streamování v HD kvalitě",
      "Zrušení kdykoliv",
    ],
  },
  {
    id: "mp2",
    tier: "VIP",
    name: "VIP",
    priceKcMonth: 399,
    highlighted: true,
    features: [
      "Vše z plánu MEMBER",
      "Prémiová VIP videa (pokročilé sestavy)",
      "Přístup k VIP kurzům se slevou 20 %",
      "Prioritní přístup k novému obsahu",
      "Zrušení kdykoliv",
    ],
  },
  {
    id: "mp3",
    tier: "VIP_PLUS",
    name: "VIP PLUS",
    priceKcMonth: 599,
    highlighted: false,
    features: [
      "Vše z plánu VIP",
      "Přímá komunikace se mnou (chat)",
      "Přístup k živým streamům",
      "Slevy na osobní lekce a akce",
      "Exkluzivní obsah VIP PLUS",
      "Zrušení kdykoliv",
    ],
  },
];
